const libraries = [
  {
    id: 1,
    name: "React",
    logo: "⚛️",
    description: "A JavaScript library for building user interfaces, maintained by Meta. Uses a declarative, component-based approach with a virtual DOM.",
    category: "ui-framework",
    tags: ["UI", "Component", "Virtual DOM", "JSX", "SPA"],
    stars: "228k",
    version: "18.3",
    website: "https://react.dev",
    github: "https://github.com/facebook/react",
    npm: "react",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 2,
    name: "Vue.js",
    logo: "💚",
    description: "A progressive JavaScript framework for building user interfaces. Designed to be incrementally adoptable with an approachable core library.",
    category: "ui-framework",
    tags: ["UI", "Component", "Progressive", "Reactive", "SPA"],
    stars: "207k",
    version: "3.4",
    website: "https://vuejs.org",
    github: "https://github.com/vuejs/core",
    npm: "vue",
    created: 2014,
    language: "JavaScript",
  },
  {
    id: 3,
    name: "Angular",
    logo: "🔺",
    description: "A platform and framework for building single-page client applications using HTML and TypeScript, developed by Google.",
    category: "ui-framework",
    tags: ["UI", "TypeScript", "SPA", "Google", "Full-framework"],
    stars: "95k",
    version: "17.3",
    website: "https://angular.io",
    github: "https://github.com/angular/angular",
    npm: "@angular/core",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 4,
    name: "Next.js",
    logo: "▲",
    description: "The React framework for production. Provides hybrid static & server rendering, TypeScript support, smart bundling, route prefetching, and more.",
    category: "meta-framework",
    tags: ["React", "SSR", "SSG", "Full-stack", "Vercel"],
    stars: "121k",
    version: "14.2",
    website: "https://nextjs.org",
    github: "https://github.com/vercel/next.js",
    npm: "next",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 5,
    name: "Svelte",
    logo: "🧡",
    description: "A radical new approach to building user interfaces. Svelte shifts work into a compile step, producing vanilla JS with no virtual DOM overhead.",
    category: "ui-framework",
    tags: ["Compiler", "No Virtual DOM", "Reactive", "Performance"],
    stars: "78k",
    version: "4.2",
    website: "https://svelte.dev",
    github: "https://github.com/sveltejs/svelte",
    npm: "svelte",
    created: 2016,
    language: "JavaScript",
  },
  {
    id: 6,
    name: "jQuery",
    logo: "🎯",
    description: "A fast, small, and feature-rich JavaScript library that simplifies HTML traversal, event handling, animation, and Ajax interactions.",
    category: "utility",
    tags: ["DOM", "Ajax", "Animation", "Legacy", "Browser"],
    stars: "59k",
    version: "3.7",
    website: "https://jquery.com",
    github: "https://github.com/jquery/jquery",
    npm: "jquery",
    created: 2006,
    language: "JavaScript",
  },
  {
    id: 7,
    name: "Express",
    logo: "🚂",
    description: "A minimal and flexible Node.js web application framework providing a robust set of features for web and mobile applications.",
    category: "backend",
    tags: ["Node.js", "Server", "REST", "Middleware", "HTTP"],
    stars: "64k",
    version: "4.19",
    website: "https://expressjs.com",
    github: "https://github.com/expressjs/express",
    npm: "express",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 8,
    name: "Lodash",
    logo: "🔧",
    description: "A modern JavaScript utility library delivering modularity, performance & extras for working with arrays, numbers, objects, strings, and more.",
    category: "utility",
    tags: ["Utility", "Arrays", "Objects", "Functions", "FP"],
    stars: "59k",
    version: "4.17",
    website: "https://lodash.com",
    github: "https://github.com/lodash/lodash",
    npm: "lodash",
    created: 2012,
    language: "JavaScript",
  },
  {
    id: 9,
    name: "Axios",
    logo: "📡",
    description: "Promise based HTTP client for the browser and Node.js with an easy-to-use API for making HTTP requests.",
    category: "utility",
    tags: ["HTTP", "Promise", "Fetch", "REST", "Node.js"],
    stars: "104k",
    version: "1.6",
    website: "https://axios-http.com",
    github: "https://github.com/axios/axios",
    npm: "axios",
    created: 2014,
    language: "JavaScript",
  },
  {
    id: 10,
    name: "D3.js",
    logo: "📊",
    description: "A JavaScript library for producing dynamic, interactive data visualizations in web browsers using HTML, SVG, and CSS.",
    category: "data-viz",
    tags: ["Data", "Charts", "SVG", "Visualization", "DOM"],
    stars: "107k",
    version: "7.9",
    website: "https://d3js.org",
    github: "https://github.com/d3/d3",
    npm: "d3",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 11,
    name: "Three.js",
    logo: "🌐",
    description: "A cross-browser JavaScript library and API used to create and display animated 3D computer graphics in a web browser using WebGL.",
    category: "graphics",
    tags: ["3D", "WebGL", "Animation", "Canvas", "Graphics"],
    stars: "99k",
    version: "r163",
    website: "https://threejs.org",
    github: "https://github.com/mrdoob/three.js",
    npm: "three",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 12,
    name: "Redux",
    logo: "🔄",
    description: "A predictable state container for JavaScript apps. Helps you write applications that behave consistently and run in different environments.",
    category: "state-management",
    tags: ["State", "React", "Flux", "Store", "Reducer"],
    stars: "60k",
    version: "5.0",
    website: "https://redux.js.org",
    github: "https://github.com/reduxjs/redux",
    npm: "redux",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 13,
    name: "Nuxt.js",
    logo: "💚",
    description: "An intuitive Vue framework providing server-side rendering, static site generation, and a powerful modular architecture.",
    category: "meta-framework",
    tags: ["Vue", "SSR", "SSG", "Full-stack", "Modules"],
    stars: "52k",
    version: "3.11",
    website: "https://nuxt.com",
    github: "https://github.com/nuxt/nuxt",
    npm: "nuxt",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 14,
    name: "Gatsby",
    logo: "🟣",
    description: "A React-based open source framework for creating websites and apps. Build anything you can imagine with over 2500 plugins.",
    category: "meta-framework",
    tags: ["React", "SSG", "GraphQL", "JAMstack", "Performance"],
    stars: "55k",
    version: "5.13",
    website: "https://www.gatsbyjs.com",
    github: "https://github.com/gatsbyjs/gatsby",
    npm: "gatsby",
    created: 2015,
    language: "JavaScript",
  },
  {
    id: 15,
    name: "RxJS",
    logo: "🔵",
    description: "A library for reactive programming using Observables, to make it easier to compose asynchronous or callback-based code.",
    category: "utility",
    tags: ["Reactive", "Observable", "Async", "Streams", "Angular"],
    stars: "30k",
    version: "7.8",
    website: "https://rxjs.dev",
    github: "https://github.com/ReactiveX/rxjs",
    npm: "rxjs",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 16,
    name: "Chart.js",
    logo: "📈",
    description: "Simple yet flexible JavaScript charting library for designers and developers, supporting 8 chart types with animations.",
    category: "data-viz",
    tags: ["Charts", "Canvas", "Visualization", "Responsive", "Animation"],
    stars: "63k",
    version: "4.4",
    website: "https://www.chartjs.org",
    github: "https://github.com/chartjs/Chart.js",
    npm: "chart.js",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 17,
    name: "GSAP",
    logo: "✨",
    description: "An industry-standard JavaScript animation library from GreenSock. Animate anything — CSS, SVG, DOM, canvas, React, Vue, WebGL, colors, strings, motion paths, generic objects.",
    category: "animation",
    tags: ["Animation", "Tweening", "Timeline", "SVG", "Performance"],
    stars: "19k",
    version: "3.12",
    website: "https://gsap.com",
    github: "https://github.com/greensock/GSAP",
    npm: "gsap",
    created: 2008,
    language: "JavaScript",
  },
  {
    id: 18,
    name: "Ember.js",
    logo: "🔥",
    description: "A productive, battle-tested JavaScript framework for building modern web applications. Includes everything you need to build rich UIs.",
    category: "ui-framework",
    tags: ["MVC", "Convention", "SPA", "Full-framework", "Router"],
    stars: "22k",
    version: "5.7",
    website: "https://emberjs.com",
    github: "https://github.com/emberjs/ember.js",
    npm: "ember-source",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 19,
    name: "Backbone.js",
    logo: "🦴",
    description: "Gives structure to web applications by providing models with key-value binding and custom events, collections, views with declarative event handling.",
    category: "ui-framework",
    tags: ["MVC", "Models", "Views", "REST", "Legacy"],
    stars: "28k",
    version: "1.4",
    website: "https://backbonejs.org",
    github: "https://github.com/jashkenas/backbone",
    npm: "backbone",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 20,
    name: "Zustand",
    logo: "🐻",
    description: "A small, fast and scalable bearbones state-management solution for React. Uses simplified flux principles with a comfortable API.",
    category: "state-management",
    tags: ["State", "React", "Lightweight", "Hooks", "Simple"],
    stars: "43k",
    version: "4.5",
    website: "https://zustand-demo.pmnd.rs",
    github: "https://github.com/pmndrs/zustand",
    npm: "zustand",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 21,
    name: "Vite",
    logo: "⚡",
    description: "Next generation frontend tooling. An extremely fast build tool and development server with instant HMR and optimized builds.",
    category: "build-tool",
    tags: ["Build", "HMR", "Dev Server", "ESM", "Bundler"],
    stars: "66k",
    version: "5.2",
    website: "https://vitejs.dev",
    github: "https://github.com/vitejs/vite",
    npm: "vite",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 22,
    name: "Webpack",
    logo: "📦",
    description: "A static module bundler for modern JavaScript applications. Builds a dependency graph of all modules your application needs.",
    category: "build-tool",
    tags: ["Bundler", "Modules", "Loaders", "Plugins", "Build"],
    stars: "64k",
    version: "5.91",
    website: "https://webpack.js.org",
    github: "https://github.com/webpack/webpack",
    npm: "webpack",
    created: 2012,
    language: "JavaScript",
  },
  {
    id: 23,
    name: "Jest",
    logo: "🃏",
    description: "A delightful JavaScript testing framework with a focus on simplicity. Works with React, Angular, Vue, Node, TypeScript, and more.",
    category: "testing",
    tags: ["Testing", "Unit Test", "Mocking", "Snapshot", "Coverage"],
    stars: "43k",
    version: "29.7",
    website: "https://jestjs.io",
    github: "https://github.com/jestjs/jest",
    npm: "jest",
    created: 2014,
    language: "TypeScript",
  },
  {
    id: 24,
    name: "Tailwind CSS",
    logo: "💨",
    description: "A utility-first CSS framework packed with classes that can be composed to build any design, directly in your markup.",
    category: "styling",
    tags: ["CSS", "Utility", "Styling", "Responsive", "Design"],
    stars: "79k",
    version: "3.4",
    website: "https://tailwindcss.com",
    github: "https://github.com/tailwindlabs/tailwindcss",
    npm: "tailwindcss",
    created: 2017,
    language: "JavaScript",
  },
  {
    id: 25,
    name: "Moment.js",
    logo: "🕐",
    description: "A JavaScript date library for parsing, validating, manipulating, and formatting dates. (Now in maintenance mode — consider alternatives.)",
    category: "utility",
    tags: ["Date", "Time", "Parsing", "Format", "Legacy"],
    stars: "47k",
    version: "2.30",
    website: "https://momentjs.com",
    github: "https://github.com/moment/moment",
    npm: "moment",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 26,
    name: "SvelteKit",
    logo: "🔶",
    description: "The fastest way to build Svelte apps. An app framework powered by Svelte with file-based routing, SSR, and API routes.",
    category: "meta-framework",
    tags: ["Svelte", "SSR", "SSG", "Full-stack", "Router"],
    stars: "18k",
    version: "2.5",
    website: "https://kit.svelte.dev",
    github: "https://github.com/sveltejs/kit",
    npm: "@sveltejs/kit",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 27,
    name: "Cypress",
    logo: "🌲",
    description: "Fast, easy and reliable testing for anything that runs in a browser. End-to-end testing, component testing, and visual regression.",
    category: "testing",
    tags: ["E2E", "Testing", "Browser", "Component", "Visual"],
    stars: "46k",
    version: "13.8",
    website: "https://www.cypress.io",
    github: "https://github.com/cypress-io/cypress",
    npm: "cypress",
    created: 2014,
    language: "TypeScript",
  },
  {
    id: 28,
    name: "Socket.IO",
    logo: "🔌",
    description: "Enables real-time, bidirectional and event-based communication between the browser and the server.",
    category: "backend",
    tags: ["WebSocket", "Real-time", "Events", "Node.js", "Chat"],
    stars: "60k",
    version: "4.7",
    website: "https://socket.io",
    github: "https://github.com/socketio/socket.io",
    npm: "socket.io",
    created: 2010,
    language: "TypeScript",
  },
  {
    id: 29,
    name: "Storybook",
    logo: "📖",
    description: "An open source tool for building UI components and pages in isolation. Streamlines UI development, testing, and documentation.",
    category: "tooling",
    tags: ["UI", "Documentation", "Component", "Testing", "Design"],
    stars: "83k",
    version: "8.0",
    website: "https://storybook.js.org",
    github: "https://github.com/storybookjs/storybook",
    npm: "storybook",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 30,
    name: "Solid.js",
    logo: "🔷",
    description: "A declarative, efficient and flexible JavaScript library for building user interfaces with fine-grained reactivity and no virtual DOM.",
    category: "ui-framework",
    tags: ["Reactive", "No Virtual DOM", "Performance", "Signals", "JSX"],
    stars: "31k",
    version: "1.8",
    website: "https://www.solidjs.com",
    github: "https://github.com/solidjs/solid",
    npm: "solid-js",
    created: 2018,
    language: "TypeScript",
  },
  {
    id: 31,
    name: "Remix",
    logo: "💿",
    description: "A full-stack web framework built on web standards that lets you focus on the user interface and work back through web fundamentals to deliver fast and resilient experiences.",
    category: "meta-framework",
    tags: ["React", "SSR", "Full-stack", "Web Standards", "Routing"],
    stars: "29k",
    version: "2.9",
    website: "https://remix.run",
    github: "https://github.com/remix-run/remix",
    npm: "@remix-run/react",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 32,
    name: "Astro",
    logo: "🚀",
    description: "The web framework for content-driven websites. Astro builds fast websites by shipping zero JavaScript by default with its unique island architecture.",
    category: "meta-framework",
    tags: ["SSG", "Islands", "Performance", "Content", "Multi-framework"],
    stars: "43k",
    version: "4.8",
    website: "https://astro.build",
    github: "https://github.com/withastro/astro",
    npm: "astro",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 33,
    name: "Vitest",
    logo: "🧪",
    description: "A blazing fast unit testing framework powered by Vite. Native ESM, TypeScript, and JSX support out of the box with a Jest-compatible API.",
    category: "testing",
    tags: ["Testing", "Unit Test", "Vite", "ESM", "Coverage"],
    stars: "12k",
    version: "1.6",
    website: "https://vitest.dev",
    github: "https://github.com/vitest-dev/vitest",
    npm: "vitest",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 34,
    name: "Playwright",
    logo: "🎭",
    description: "A reliable end-to-end testing framework for modern web apps. Supports Chromium, Firefox, and WebKit with a single API across all platforms.",
    category: "testing",
    tags: ["E2E", "Testing", "Browser", "Cross-browser", "Automation"],
    stars: "63k",
    version: "1.44",
    website: "https://playwright.dev",
    github: "https://github.com/microsoft/playwright",
    npm: "@playwright/test",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 35,
    name: "Jotai",
    logo: "⚛️",
    description: "Primitive and flexible state management for React. Takes a bottom-up atomic approach to global React state management with a minimal API.",
    category: "state-management",
    tags: ["State", "React", "Atomic", "Hooks", "Lightweight"],
    stars: "17k",
    version: "2.8",
    website: "https://jotai.org",
    github: "https://github.com/pmndrs/jotai",
    npm: "jotai",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 36,
    name: "MobX",
    logo: "🔮",
    description: "Simple, scalable state management. MobX makes state management simple by transparently applying functional reactive programming principles.",
    category: "state-management",
    tags: ["State", "Reactive", "Observable", "Decorators", "OOP"],
    stars: "27k",
    version: "6.12",
    website: "https://mobx.js.org",
    github: "https://github.com/mobxjs/mobx",
    npm: "mobx",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 37,
    name: "TanStack Query",
    logo: "🔍",
    description: "Powerful asynchronous state management for React, Vue, Solid, and Svelte. Often called React Query, it simplifies fetching, caching, syncing, and updating server state.",
    category: "utility",
    tags: ["Data Fetching", "Caching", "Async", "Server State", "React"],
    stars: "39k",
    version: "5.40",
    website: "https://tanstack.com/query",
    github: "https://github.com/TanStack/query",
    npm: "@tanstack/react-query",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 38,
    name: "Zod",
    logo: "🛡️",
    description: "TypeScript-first schema declaration and validation library. Define schemas once and use them for both TypeScript types and runtime validation.",
    category: "utility",
    tags: ["Validation", "TypeScript", "Schema", "Types", "Parsing"],
    stars: "31k",
    version: "3.23",
    website: "https://zod.dev",
    github: "https://github.com/colinhacks/zod",
    npm: "zod",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 39,
    name: "Framer Motion",
    logo: "🎬",
    description: "A production-ready motion library for React. Provides a simple, declarative API for animations and gestures, from simple transitions to complex orchestrations.",
    category: "animation",
    tags: ["Animation", "React", "Gestures", "Motion", "Transitions"],
    stars: "23k",
    version: "11.2",
    website: "https://www.framer.com/motion",
    github: "https://github.com/framer/motion",
    npm: "framer-motion",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 40,
    name: "Anime.js",
    logo: "✏️",
    description: "A lightweight JavaScript animation library with a simple yet powerful API. Animate CSS properties, SVG, DOM attributes, and JavaScript objects.",
    category: "animation",
    tags: ["Animation", "CSS", "SVG", "Lightweight", "Timeline"],
    stars: "49k",
    version: "3.2",
    website: "https://animejs.com",
    github: "https://github.com/juliangarnier/anime",
    npm: "animejs",
    created: 2016,
    language: "JavaScript",
  },
  {
    id: 41,
    name: "PixiJS",
    logo: "🎮",
    description: "The HTML5 Creation Engine. Create beautiful digital content with the fastest, most flexible 2D WebGL renderer, with a fallback to HTML5 Canvas.",
    category: "graphics",
    tags: ["2D", "WebGL", "Canvas", "Rendering", "Games"],
    stars: "43k",
    version: "8.1",
    website: "https://pixijs.com",
    github: "https://github.com/pixijs/pixijs",
    npm: "pixi.js",
    created: 2013,
    language: "TypeScript",
  },
  {
    id: 42,
    name: "Fastify",
    logo: "⚡",
    description: "Fast and low overhead web framework for Node.js. One of the fastest web frameworks available, with a rich plugin ecosystem and great developer experience.",
    category: "backend",
    tags: ["Node.js", "HTTP", "REST", "Performance", "Plugins"],
    stars: "31k",
    version: "4.27",
    website: "https://fastify.dev",
    github: "https://github.com/fastify/fastify",
    npm: "fastify",
    created: 2016,
    language: "JavaScript",
  },
  {
    id: 43,
    name: "NestJS",
    logo: "🐈",
    description: "A progressive Node.js framework for building efficient, reliable and scalable server-side applications. Built with TypeScript and heavily inspired by Angular.",
    category: "backend",
    tags: ["Node.js", "TypeScript", "Enterprise", "Decorators", "Modules"],
    stars: "66k",
    version: "10.3",
    website: "https://nestjs.com",
    github: "https://github.com/nestjs/nest",
    npm: "@nestjs/core",
    created: 2017,
    language: "TypeScript",
  },
  {
    id: 44,
    name: "Mongoose",
    logo: "🍃",
    description: "Elegant MongoDB object modeling for Node.js. Provides a straightforward, schema-based solution to model application data with built-in type casting and validation.",
    category: "backend",
    tags: ["MongoDB", "ODM", "Node.js", "Schema", "Database"],
    stars: "26k",
    version: "8.4",
    website: "https://mongoosejs.com",
    github: "https://github.com/Automattic/mongoose",
    npm: "mongoose",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 45,
    name: "Day.js",
    logo: "📅",
    description: "A minimalist 2kB JavaScript library that parses, validates, manipulates, and displays dates and times for modern browsers with a largely Moment.js-compatible API.",
    category: "utility",
    tags: ["Date", "Time", "Lightweight", "Immutable", "i18n"],
    stars: "46k",
    version: "1.11",
    website: "https://day.js.org",
    github: "https://github.com/iamkun/dayjs",
    npm: "dayjs",
    created: 2018,
    language: "JavaScript",
  },
  {
    id: 46,
    name: "styled-components",
    logo: "💅",
    description: "Visual primitives for the component age. Uses tagged template literals to style React components, keeping CSS co-located with the component that uses it.",
    category: "styling",
    tags: ["CSS-in-JS", "React", "Theming", "Dynamic Styles", "Component"],
    stars: "40k",
    version: "6.1",
    website: "https://styled-components.com",
    github: "https://github.com/styled-components/styled-components",
    npm: "styled-components",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 47,
    name: "Rollup",
    logo: "📜",
    description: "A module bundler for JavaScript which compiles small pieces of code into something larger and more complex. Ideal for library authors thanks to its tree-shaking.",
    category: "build-tool",
    tags: ["Bundler", "ESM", "Tree-shaking", "Library", "Modules"],
    stars: "24k",
    version: "4.18",
    website: "https://rollupjs.org",
    github: "https://github.com/rollup/rollup",
    npm: "rollup",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 48,
    name: "esbuild",
    logo: "⚡",
    description: "An extremely fast JavaScript and TypeScript bundler and minifier, written in Go. 10–100x faster than other bundlers, used as the core of many modern tools.",
    category: "build-tool",
    tags: ["Bundler", "Fast", "Go", "Minifier", "TypeScript"],
    stars: "37k",
    version: "0.21",
    website: "https://esbuild.github.io",
    github: "https://github.com/evanw/esbuild",
    npm: "esbuild",
    created: 2020,
    language: "Go",
  },
  {
    id: 49,
    name: "Prettier",
    logo: "✨",
    description: "An opinionated code formatter that supports many languages. Enforces a consistent style by parsing your code and reprinting it with its own rules.",
    category: "tooling",
    tags: ["Formatter", "Code Style", "Linting", "Multi-language", "Opinionated"],
    stars: "48k",
    version: "3.3",
    website: "https://prettier.io",
    github: "https://github.com/prettier/prettier",
    npm: "prettier",
    created: 2017,
    language: "JavaScript",
  },
  {
    id: 50,
    name: "ESLint",
    logo: "🔍",
    description: "Find and fix problems in your JavaScript code. A fully pluggable tool for identifying and reporting on patterns in ECMAScript/JavaScript code.",
    category: "tooling",
    tags: ["Linting", "Code Quality", "Rules", "Plugins", "ECMAScript"],
    stars: "24k",
    version: "9.4",
    website: "https://eslint.org",
    github: "https://github.com/eslint/eslint",
    npm: "eslint",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 51,
    name: "Preact",
    logo: "⚛️",
    description: "A fast 3kB alternative to React with the same modern API. Preact offers the thinnest possible Virtual DOM abstraction on top of the DOM.",
    category: "ui-framework",
    tags: ["UI", "Virtual DOM", "Lightweight", "React-compatible", "Performance"],
    stars: "36k",
    version: "10.22",
    website: "https://preactjs.com",
    github: "https://github.com/preactjs/preact",
    npm: "preact",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 52,
    name: "Alpine.js",
    logo: "🏔️",
    description: "A rugged, minimal framework for composing JavaScript behavior in your HTML. Think of it like jQuery for the modern web.",
    category: "ui-framework",
    tags: ["Lightweight", "HTML", "Declarative", "Minimal", "No Build"],
    stars: "27k",
    version: "3.14",
    website: "https://alpinejs.dev",
    github: "https://github.com/alpinejs/alpine",
    npm: "alpinejs",
    created: 2019,
    language: "JavaScript",
  },
  {
    id: 53,
    name: "Lit",
    logo: "🔥",
    description: "A simple library for building fast, lightweight web components. Lit uses standard web platform features to build reusable, interoperable elements.",
    category: "ui-framework",
    tags: ["Web Components", "Lightweight", "Standards", "Reactive", "Shadow DOM"],
    stars: "18k",
    version: "3.1",
    website: "https://lit.dev",
    github: "https://github.com/lit/lit",
    npm: "lit",
    created: 2018,
    language: "TypeScript",
  },
  {
    id: 54,
    name: "Qwik",
    logo: "⚡",
    description: "A new kind of web framework that can deliver instant loading web applications at any size or complexity. Achieves sub-second load times via resumability.",
    category: "ui-framework",
    tags: ["Resumable", "Performance", "SSR", "Lazy Loading", "No Hydration"],
    stars: "20k",
    version: "1.5",
    website: "https://qwik.dev",
    github: "https://github.com/QwikDev/qwik",
    npm: "@builder.io/qwik",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 55,
    name: "Stencil",
    logo: "🎸",
    description: "A toolchain for building reusable, scalable design systems and web components. Generates standards-based web components that run in every major browser.",
    category: "ui-framework",
    tags: ["Web Components", "Design System", "TypeScript", "Compiler", "Cross-framework"],
    stars: "12k",
    version: "4.19",
    website: "https://stenciljs.com",
    github: "https://github.com/ionic-team/stencil",
    npm: "@stencil/core",
    created: 2017,
    language: "TypeScript",
  },
  {
    id: 56,
    name: "Recoil",
    logo: "⚛️",
    description: "An experimental state management library for React apps. Provides several capabilities that are difficult to achieve with React alone, like derived data and queries.",
    category: "state-management",
    tags: ["State", "React", "Atomic", "Selectors", "Facebook"],
    stars: "19k",
    version: "0.7",
    website: "https://recoiljs.org",
    github: "https://github.com/facebookexperimental/Recoil",
    npm: "recoil",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 57,
    name: "XState",
    logo: "🤖",
    description: "State machines and statecharts for the modern web. A library for creating, interpreting, and executing finite state machines and statecharts.",
    category: "state-management",
    tags: ["State Machine", "Statechart", "Actor Model", "Visual", "Finite State"],
    stars: "26k",
    version: "5.13",
    website: "https://xstate.js.org",
    github: "https://github.com/statelyai/xstate",
    npm: "xstate",
    created: 2017,
    language: "TypeScript",
  },
  {
    id: 58,
    name: "Pinia",
    logo: "🍍",
    description: "The intuitive store for Vue.js. A type-safe, extensible, and modular store with devtools support. The official successor to Vuex.",
    category: "state-management",
    tags: ["State", "Vue", "TypeScript", "Composition API", "Devtools"],
    stars: "12k",
    version: "2.1",
    website: "https://pinia.vuejs.org",
    github: "https://github.com/vuejs/pinia",
    npm: "pinia",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 59,
    name: "Vuex",
    logo: "💚",
    description: "A state management pattern + library for Vue.js applications. Serves as a centralized store for all components in an application.",
    category: "state-management",
    tags: ["State", "Vue", "Flux", "Store", "Mutations"],
    stars: "28k",
    version: "4.1",
    website: "https://vuex.vuejs.org",
    github: "https://github.com/vuejs/vuex",
    npm: "vuex",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 60,
    name: "Nano Stores",
    logo: "🔬",
    description: "A tiny state manager for React, Vue, Svelte, Solid, and vanilla JS. Designed with tree shaking in mind, so each tiny store is only 265 bytes.",
    category: "state-management",
    tags: ["State", "Tiny", "Framework-agnostic", "Tree-shaking", "Atoms"],
    stars: "4k",
    version: "0.11",
    website: "https://github.com/nanostores/nanostores",
    github: "https://github.com/nanostores/nanostores",
    npm: "nanostores",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 61,
    name: "Hono",
    logo: "🔥",
    description: "A small, simple, and ultrafast web framework for the Edges. Works on Cloudflare Workers, Fastly Compute, Deno, Bun, Vercel, and Node.js.",
    category: "backend",
    tags: ["Edge", "Cloudflare", "Fast", "Lightweight", "TypeScript"],
    stars: "18k",
    version: "4.4",
    website: "https://hono.dev",
    github: "https://github.com/honojs/hono",
    npm: "hono",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 62,
    name: "Koa",
    logo: "🍵",
    description: "Next generation web framework for Node.js. A lightweight and expressive HTTP middleware framework that improves on Express using async functions.",
    category: "backend",
    tags: ["Node.js", "Middleware", "Async", "HTTP", "Lightweight"],
    stars: "35k",
    version: "2.15",
    website: "https://koajs.com",
    github: "https://github.com/koajs/koa",
    npm: "koa",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 63,
    name: "Hapi",
    logo: "🎩",
    description: "The simple, secure framework for Node.js. Built for enterprise-grade applications, hapi provides rich, easy-to-use APIs for building powerful applications.",
    category: "backend",
    tags: ["Node.js", "Enterprise", "Security", "Plugins", "Validation"],
    stars: "14k",
    version: "21.3",
    website: "https://hapi.dev",
    github: "https://github.com/hapijs/hapi",
    npm: "@hapi/hapi",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 64,
    name: "Prisma",
    logo: "💎",
    description: "Next-generation Node.js and TypeScript ORM. Auto-generated, type-safe query builder that provides database access with an intuitive data model and migrations.",
    category: "backend",
    tags: ["ORM", "TypeScript", "Database", "Migrations", "Type-safe"],
    stars: "38k",
    version: "5.15",
    website: "https://www.prisma.io",
    github: "https://github.com/prisma/prisma",
    npm: "@prisma/client",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 65,
    name: "Sequelize",
    logo: "🐘",
    description: "A feature-rich ORM for Node.js supporting PostgreSQL, MySQL, MariaDB, SQLite, and more. Provides solid transaction support, relations, eager loading, and more.",
    category: "backend",
    tags: ["ORM", "SQL", "Node.js", "PostgreSQL", "MySQL"],
    stars: "29k",
    version: "6.37",
    website: "https://sequelize.org",
    github: "https://github.com/sequelize/sequelize",
    npm: "sequelize",
    created: 2010,
    language: "TypeScript",
  },
  {
    id: 66,
    name: "TypeORM",
    logo: "🗄️",
    description: "An ORM that runs in Node.js and can be used with TypeScript and JavaScript. Supports Active Record and Data Mapper patterns, multiple databases, and migrations.",
    category: "backend",
    tags: ["ORM", "TypeScript", "SQL", "Decorators", "Migrations"],
    stars: "34k",
    version: "0.3",
    website: "https://typeorm.io",
    github: "https://github.com/typeorm/typeorm",
    npm: "typeorm",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 67,
    name: "Drizzle ORM",
    logo: "💧",
    description: "A headless TypeScript ORM that is the source of truth for your SQL schema. Lightweight, performant, and fully type-safe with zero dependencies.",
    category: "backend",
    tags: ["ORM", "TypeScript", "SQL", "Lightweight", "Type-safe"],
    stars: "22k",
    version: "0.31",
    website: "https://orm.drizzle.team",
    github: "https://github.com/drizzle-team/drizzle-orm",
    npm: "drizzle-orm",
    created: 2022,
    language: "TypeScript",
  },
  {
    id: 68,
    name: "Apollo Client",
    logo: "🚀",
    description: "A comprehensive state management library for JavaScript that enables you to manage both local and remote data with GraphQL.",
    category: "utility",
    tags: ["GraphQL", "State", "Caching", "React", "Data Fetching"],
    stars: "19k",
    version: "3.10",
    website: "https://www.apollographql.com/docs/react",
    github: "https://github.com/apollographql/apollo-client",
    npm: "@apollo/client",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 69,
    name: "tRPC",
    logo: "🔗",
    description: "End-to-end typesafe APIs made easy. Move fast and break nothing — write your API once and share types between client and server automatically.",
    category: "utility",
    tags: ["TypeScript", "API", "Type-safe", "Full-stack", "RPC"],
    stars: "33k",
    version: "11.0",
    website: "https://trpc.io",
    github: "https://github.com/trpc/trpc",
    npm: "@trpc/server",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 70,
    name: "date-fns",
    logo: "📅",
    description: "Modern JavaScript date utility library. Provides the most comprehensive, yet simple and consistent toolset for manipulating JavaScript dates.",
    category: "utility",
    tags: ["Date", "Time", "Modular", "Immutable", "FP"],
    stars: "34k",
    version: "3.6",
    website: "https://date-fns.org",
    github: "https://github.com/date-fns/date-fns",
    npm: "date-fns",
    created: 2014,
    language: "TypeScript",
  },
  {
    id: 71,
    name: "Ramda",
    logo: "🐏",
    description: "A practical functional library for JavaScript programmers. Emphasizes immutability, side-effect free functions, and automatic currying.",
    category: "utility",
    tags: ["Functional", "Currying", "Immutable", "Composition", "FP"],
    stars: "23k",
    version: "0.30",
    website: "https://ramdajs.com",
    github: "https://github.com/ramda/ramda",
    npm: "ramda",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 72,
    name: "Immer",
    logo: "🧊",
    description: "Create the next immutable state by mutating the current one. Allows you to work with immutable state in a more convenient way using a simple copy-on-write mechanism.",
    category: "utility",
    tags: ["Immutable", "State", "Proxy", "React", "Copy-on-write"],
    stars: "27k",
    version: "10.1",
    website: "https://immerjs.github.io/immer",
    github: "https://github.com/immerjs/immer",
    npm: "immer",
    created: 2018,
    language: "TypeScript",
  },
  {
    id: 73,
    name: "dotenv",
    logo: "🔐",
    description: "A zero-dependency module that loads environment variables from a .env file into process.env. Keeps configuration separate from code following 12-factor app methodology.",
    category: "utility",
    tags: ["Environment", "Config", "Node.js", "Security", "12-factor"],
    stars: "18k",
    version: "16.4",
    website: "https://github.com/motdotla/dotenv",
    github: "https://github.com/motdotla/dotenv",
    npm: "dotenv",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 74,
    name: "uuid",
    logo: "🆔",
    description: "Simple, fast generation of RFC4122 UUIDs. Supports versions 1, 3, 4, 5, 6, 7, and 8. The most widely used UUID generation library for JavaScript.",
    category: "utility",
    tags: ["UUID", "GUID", "ID Generation", "RFC4122", "Unique"],
    stars: "14k",
    version: "10.0",
    website: "https://github.com/uuidjs/uuid",
    github: "https://github.com/uuidjs/uuid",
    npm: "uuid",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 75,
    name: "Marked",
    logo: "📝",
    description: "A low-level markdown compiler for parsing markdown without caching or blocking for long periods of time. Built for speed and designed for use in browsers and Node.js.",
    category: "utility",
    tags: ["Markdown", "Parser", "Compiler", "HTML", "Content"],
    stars: "33k",
    version: "12.0",
    website: "https://marked.js.org",
    github: "https://github.com/markedjs/marked",
    npm: "marked",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 76,
    name: "highlight.js",
    logo: "🎨",
    description: "The internet's most widely deployed syntax highlighter. Automatic language detection, 200+ languages, available for Node and browser environments.",
    category: "utility",
    tags: ["Syntax Highlight", "Code", "Language Detection", "Themes", "Browser"],
    stars: "23k",
    version: "11.9",
    website: "https://highlightjs.org",
    github: "https://github.com/highlightjs/highlight.js",
    npm: "highlight.js",
    created: 2006,
    language: "JavaScript",
  },
  {
    id: 77,
    name: "Fuse.js",
    logo: "🔎",
    description: "Powerful, lightweight fuzzy-search library, with zero dependencies. Searches large collections of text quickly and efficiently, even with typos.",
    category: "utility",
    tags: ["Search", "Fuzzy", "Lightweight", "Zero Dependencies", "Text"],
    stars: "17k",
    version: "7.0",
    website: "https://www.fusejs.io",
    github: "https://github.com/krisk/Fuse",
    npm: "fuse.js",
    created: 2012,
    language: "TypeScript",
  },
  {
    id: 78,
    name: "Leaflet",
    logo: "🗺️",
    description: "The leading open-source JavaScript library for mobile-friendly interactive maps. Lightweight, simple, and flexible with a plugin ecosystem.",
    category: "data-viz",
    tags: ["Maps", "GIS", "Interactive", "Mobile", "Tiles"],
    stars: "40k",
    version: "1.9",
    website: "https://leafletjs.com",
    github: "https://github.com/Leaflet/Leaflet",
    npm: "leaflet",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 79,
    name: "Recharts",
    logo: "📉",
    description: "A composable charting library built on React components. Leverages D3 for calculations and SVG for rendering, offering a declarative API for charts.",
    category: "data-viz",
    tags: ["Charts", "React", "SVG", "D3", "Composable"],
    stars: "23k",
    version: "2.12",
    website: "https://recharts.org",
    github: "https://github.com/recharts/recharts",
    npm: "recharts",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 80,
    name: "Highcharts",
    logo: "📊",
    description: "A feature-rich JavaScript charting library for creating interactive charts in any web or mobile project. Supports 40+ chart types with rich customization.",
    category: "data-viz",
    tags: ["Charts", "Interactive", "Commercial", "Export", "Accessibility"],
    stars: "11k",
    version: "11.4",
    website: "https://www.highcharts.com",
    github: "https://github.com/highcharts/highcharts",
    npm: "highcharts",
    created: 2009,
    language: "TypeScript",
  },
  {
    id: 81,
    name: "Babylon.js",
    logo: "🏛️",
    description: "A powerful, beautiful, simple, and open game and rendering engine packed into a friendly JavaScript framework. One of the most complete WebGL game engines.",
    category: "graphics",
    tags: ["3D", "WebGL", "Game Engine", "Physics", "XR"],
    stars: "23k",
    version: "7.7",
    website: "https://www.babylonjs.com",
    github: "https://github.com/BabylonJS/Babylon.js",
    npm: "babylonjs",
    created: 2013,
    language: "TypeScript",
  },
  {
    id: 82,
    name: "p5.js",
    logo: "🎨",
    description: "A JavaScript library for creative coding, with a focus on making coding accessible and inclusive for artists, designers, educators, and beginners.",
    category: "graphics",
    tags: ["Creative Coding", "Canvas", "Art", "Education", "Visualization"],
    stars: "21k",
    version: "1.9",
    website: "https://p5js.org",
    github: "https://github.com/processing/p5.js",
    npm: "p5",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 83,
    name: "Lottie-web",
    logo: "🎞️",
    description: "A library to parse Adobe After Effects animations exported as JSON with bodymovin and renders them natively on mobile and web.",
    category: "animation",
    tags: ["After Effects", "Animation", "JSON", "SVG", "Canvas"],
    stars: "29k",
    version: "5.12",
    website: "https://airbnb.design/lottie",
    github: "https://github.com/airbnb/lottie-web",
    npm: "lottie-web",
    created: 2015,
    language: "JavaScript",
  },
  {
    id: 84,
    name: "Motion One",
    logo: "🎬",
    description: "A new animation library built on the Web Animations API, providing a simple syntax, optimized performance, and tiny bundle size.",
    category: "animation",
    tags: ["Animation", "Web Animations API", "Lightweight", "Performance", "CSS"],
    stars: "10k",
    version: "10.17",
    website: "https://motion.dev",
    github: "https://github.com/motiondivision/motionone",
    npm: "motion",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 85,
    name: "Swiper",
    logo: "👆",
    description: "The most modern free mobile touch slider with hardware accelerated transitions and amazing native behavior. Used in mobile websites, mobile web apps, and mobile native/hybrid apps.",
    category: "utility",
    tags: ["Slider", "Touch", "Mobile", "Carousel", "Responsive"],
    stars: "38k",
    version: "11.1",
    website: "https://swiperjs.com",
    github: "https://github.com/nolimits4web/swiper",
    npm: "swiper",
    created: 2012,
    language: "TypeScript",
  },
  {
    id: 86,
    name: "Sortable.js",
    logo: "↕️",
    description: "A JavaScript library for reorderable drag-and-drop lists on modern browsers and touch devices. No jQuery required, supports Angular, React, Vue, and more.",
    category: "utility",
    tags: ["Drag and Drop", "Sorting", "Touch", "Lists", "Framework-agnostic"],
    stars: "29k",
    version: "1.15",
    website: "https://sortablejs.github.io/Sortable",
    github: "https://github.com/SortableJS/Sortable",
    npm: "sortablejs",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 87,
    name: "Papa Parse",
    logo: "📋",
    description: "The powerful, in-browser CSV parser for big boys and girls. It is the fastest JavaScript CSV parser and one of the most feature-complete.",
    category: "utility",
    tags: ["CSV", "Parser", "Streaming", "Workers", "Data"],
    stars: "12k",
    version: "5.4",
    website: "https://www.papaparse.com",
    github: "https://github.com/mholt/PapaParse",
    npm: "papaparse",
    created: 2014,
    language: "JavaScript",
  },
  {
    id: 88,
    name: "JSZip",
    logo: "🗜️",
    description: "A JavaScript library for creating, reading, and editing .zip files with a lovely and simple API. Works in both browser and Node.js environments.",
    category: "utility",
    tags: ["ZIP", "Compression", "Files", "Browser", "Node.js"],
    stars: "9k",
    version: "3.10",
    website: "https://stuk.github.io/jszip",
    github: "https://github.com/Stuk/jszip",
    npm: "jszip",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 89,
    name: "Quill",
    logo: "✒️",
    description: "A powerful rich text editor built for compatibility and extensibility. Its modular architecture allows for deep customization of its behavior and appearance.",
    category: "utility",
    tags: ["Rich Text", "Editor", "WYSIWYG", "Modular", "Delta"],
    stars: "42k",
    version: "2.0",
    website: "https://quilljs.com",
    github: "https://github.com/quilljs/quill",
    npm: "quill",
    created: 2012,
    language: "TypeScript",
  },
  {
    id: 90,
    name: "Tiptap",
    logo: "📄",
    description: "A headless, framework-agnostic and extendable rich text editor, based on ProseMirror. Bring your own design, fully customizable with 100+ extensions.",
    category: "utility",
    tags: ["Rich Text", "Editor", "Headless", "ProseMirror", "Collaborative"],
    stars: "27k",
    version: "2.4",
    website: "https://tiptap.dev",
    github: "https://github.com/ueberdosis/tiptap",
    npm: "@tiptap/core",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 91,
    name: "htmx",
    logo: "💡",
    description: "High power tools for HTML. Access AJAX, CSS Transitions, WebSockets and Server Sent Events directly in HTML, using attributes, to build modern user interfaces.",
    category: "utility",
    tags: ["AJAX", "Hypermedia", "HTML", "No JavaScript", "SSR"],
    stars: "36k",
    version: "2.0",
    website: "https://htmx.org",
    github: "https://github.com/bigskysoftware/htmx",
    npm: "htmx.org",
    created: 2020,
    language: "JavaScript",
  },
  {
    id: 92,
    name: "Parcel",
    logo: "📦",
    description: "The zero configuration build tool for the web. Build code without configuration — automatic transforms, code splitting, hot module replacement, and more.",
    category: "build-tool",
    tags: ["Bundler", "Zero Config", "HMR", "Code Splitting", "Build"],
    stars: "43k",
    version: "2.12",
    website: "https://parceljs.org",
    github: "https://github.com/parcel-bundler/parcel",
    npm: "parcel",
    created: 2017,
    language: "JavaScript",
  },
  {
    id: 93,
    name: "Babel",
    logo: "🔄",
    description: "A JavaScript compiler that converts modern JavaScript into backward-compatible versions for older environments. Also supports JSX, TypeScript, and custom transforms.",
    category: "build-tool",
    tags: ["Transpiler", "Compiler", "JSX", "Polyfill", "ECMAScript"],
    stars: "43k",
    version: "7.24",
    website: "https://babeljs.io",
    github: "https://github.com/babel/babel",
    npm: "@babel/core",
    created: 2014,
    language: "JavaScript",
  },
  {
    id: 94,
    name: "TypeScript",
    logo: "🔷",
    description: "A strongly typed programming language that builds on JavaScript, giving you better tooling at any scale. Developed and maintained by Microsoft.",
    category: "tooling",
    tags: ["TypeScript", "Types", "Compiler", "Microsoft", "Static Analysis"],
    stars: "99k",
    version: "5.5",
    website: "https://www.typescriptlang.org",
    github: "https://github.com/microsoft/TypeScript",
    npm: "typescript",
    created: 2012,
    language: "TypeScript",
  },
  {
    id: 95,
    name: "Husky",
    logo: "🐶",
    description: "Modern native Git hooks made easy. Automatically lint your commit messages, code, and run tests upon committing or pushing to ensure code quality.",
    category: "tooling",
    tags: ["Git Hooks", "Linting", "Pre-commit", "Automation", "Quality"],
    stars: "32k",
    version: "9.0",
    website: "https://typicode.github.io/husky",
    github: "https://github.com/typicode/husky",
    npm: "husky",
    created: 2014,
    language: "JavaScript",
  },
  {
    id: 96,
    name: "Testing Library",
    logo: "🦑",
    description: "Simple and complete testing utilities that encourage good testing practices. Tests mirror how software is actually used by querying the DOM as users would.",
    category: "testing",
    tags: ["Testing", "DOM", "React", "Accessibility", "User-centric"],
    stars: "19k",
    version: "16.0",
    website: "https://testing-library.com",
    github: "https://github.com/testing-library/dom-testing-library",
    npm: "@testing-library/dom",
    created: 2018,
    language: "TypeScript",
  },
  {
    id: 97,
    name: "Puppeteer",
    logo: "🤖",
    description: "A Node.js library which provides a high-level API to control Chrome or Chromium over the DevTools Protocol. Ideal for scraping, screenshots, and testing.",
    category: "testing",
    tags: ["Chrome", "Automation", "Scraping", "Screenshots", "Headless"],
    stars: "87k",
    version: "22.10",
    website: "https://pptr.dev",
    github: "https://github.com/puppeteer/puppeteer",
    npm: "puppeteer",
    created: 2017,
    language: "TypeScript",
  },
  {
    id: 98,
    name: "Turbo",
    logo: "🏎️",
    description: "Turbo uses complementary techniques to dramatically speed up page loads and form submissions without requiring you to write any JavaScript. Part of Hotwire.",
    category: "utility",
    tags: ["Hotwire", "HTML", "Performance", "SPA-like", "Rails"],
    stars: "6k",
    version: "8.0",
    website: "https://turbo.hotwired.dev",
    github: "https://github.com/hotwired/turbo",
    npm: "@hotwired/turbo",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 99,
    name: "Bun",
    logo: "🍞",
    description: "An all-in-one JavaScript runtime and toolkit designed for speed. Ships with a package manager, bundler, test runner, and Node.js-compatible runtime.",
    category: "tooling",
    tags: ["Runtime", "Fast", "Bundler", "Test Runner", "Node.js compatible"],
    stars: "73k",
    version: "1.1",
    website: "https://bun.sh",
    github: "https://github.com/oven-sh/bun",
    npm: "bun-types",
    created: 2022,
    language: "TypeScript",
  },
  {
    id: 100,
    name: "Deno",
    logo: "🦕",
    description: "A modern runtime for JavaScript and TypeScript that uses V8 and is built in Rust. Designed to be a productive and secure scripting environment.",
    category: "tooling",
    tags: ["Runtime", "Secure", "TypeScript", "Web Standards", "Modern"],
    stars: "93k",
    version: "1.44",
    website: "https://deno.com",
    github: "https://github.com/denoland/deno",
    npm: "deno",
    created: 2018,
    language: "TypeScript",
  },
];

const categories = [
  { id: "all", label: "All Libraries" },
  { id: "ui-framework", label: "UI Frameworks" },
  { id: "meta-framework", label: "Meta Frameworks" },
  { id: "state-management", label: "State Management" },
  { id: "utility", label: "Utilities" },
  { id: "backend", label: "Backend" },
  { id: "data-viz", label: "Data Visualization" },
  { id: "animation", label: "Animation" },
  { id: "graphics", label: "3D & Graphics" },
  { id: "build-tool", label: "Build Tools" },
  { id: "testing", label: "Testing" },
  { id: "styling", label: "Styling" },
  { id: "tooling", label: "Tooling" },
];
