const libraries = [
  {
    id: 1,
    name: "React",
    logo: "⚛️",
    description: "A JavaScript library for building user interfaces, maintained by Meta. Uses a declarative, component-based approach with a virtual DOM.",
    category: "ui-framework",
    tags: ["UI", "Component", "Virtual DOM", "JSX", "SPA"],
    stars: "228k",
    version: "18.3",
    website: "https://react.dev",
    github: "https://github.com/facebook/react",
    npm: "react",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 2,
    name: "Vue.js",
    logo: "💚",
    description: "A progressive JavaScript framework for building user interfaces. Designed to be incrementally adoptable with an approachable core library.",
    category: "ui-framework",
    tags: ["UI", "Component", "Progressive", "Reactive", "SPA"],
    stars: "207k",
    version: "3.4",
    website: "https://vuejs.org",
    github: "https://github.com/vuejs/core",
    npm: "vue",
    created: 2014,
    language: "JavaScript",
  },
  {
    id: 3,
    name: "Angular",
    logo: "🔺",
    description: "A platform and framework for building single-page client applications using HTML and TypeScript, developed by Google.",
    category: "ui-framework",
    tags: ["UI", "TypeScript", "SPA", "Google", "Full-framework"],
    stars: "95k",
    version: "17.3",
    website: "https://angular.io",
    github: "https://github.com/angular/angular",
    npm: "@angular/core",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 4,
    name: "Next.js",
    logo: "▲",
    description: "The React framework for production. Provides hybrid static & server rendering, TypeScript support, smart bundling, route prefetching, and more.",
    category: "meta-framework",
    tags: ["React", "SSR", "SSG", "Full-stack", "Vercel"],
    stars: "121k",
    version: "14.2",
    website: "https://nextjs.org",
    github: "https://github.com/vercel/next.js",
    npm: "next",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 5,
    name: "Svelte",
    logo: "🧡",
    description: "A radical new approach to building user interfaces. Svelte shifts work into a compile step, producing vanilla JS with no virtual DOM overhead.",
    category: "ui-framework",
    tags: ["Compiler", "No Virtual DOM", "Reactive", "Performance"],
    stars: "78k",
    version: "4.2",
    website: "https://svelte.dev",
    github: "https://github.com/sveltejs/svelte",
    npm: "svelte",
    created: 2016,
    language: "JavaScript",
  },
  {
    id: 6,
    name: "jQuery",
    logo: "🎯",
    description: "A fast, small, and feature-rich JavaScript library that simplifies HTML traversal, event handling, animation, and Ajax interactions.",
    category: "utility",
    tags: ["DOM", "Ajax", "Animation", "Legacy", "Browser"],
    stars: "59k",
    version: "3.7",
    website: "https://jquery.com",
    github: "https://github.com/jquery/jquery",
    npm: "jquery",
    created: 2006,
    language: "JavaScript",
  },
  {
    id: 7,
    name: "Express",
    logo: "🚂",
    description: "A minimal and flexible Node.js web application framework providing a robust set of features for web and mobile applications.",
    category: "backend",
    tags: ["Node.js", "Server", "REST", "Middleware", "HTTP"],
    stars: "64k",
    version: "4.19",
    website: "https://expressjs.com",
    github: "https://github.com/expressjs/express",
    npm: "express",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 8,
    name: "Lodash",
    logo: "🔧",
    description: "A modern JavaScript utility library delivering modularity, performance & extras for working with arrays, numbers, objects, strings, and more.",
    category: "utility",
    tags: ["Utility", "Arrays", "Objects", "Functions", "FP"],
    stars: "59k",
    version: "4.17",
    website: "https://lodash.com",
    github: "https://github.com/lodash/lodash",
    npm: "lodash",
    created: 2012,
    language: "JavaScript",
  },
  {
    id: 9,
    name: "Axios",
    logo: "📡",
    description: "Promise based HTTP client for the browser and Node.js with an easy-to-use API for making HTTP requests.",
    category: "utility",
    tags: ["HTTP", "Promise", "Fetch", "REST", "Node.js"],
    stars: "104k",
    version: "1.6",
    website: "https://axios-http.com",
    github: "https://github.com/axios/axios",
    npm: "axios",
    created: 2014,
    language: "JavaScript",
  },
  {
    id: 10,
    name: "D3.js",
    logo: "📊",
    description: "A JavaScript library for producing dynamic, interactive data visualizations in web browsers using HTML, SVG, and CSS.",
    category: "data-viz",
    tags: ["Data", "Charts", "SVG", "Visualization", "DOM"],
    stars: "107k",
    version: "7.9",
    website: "https://d3js.org",
    github: "https://github.com/d3/d3",
    npm: "d3",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 11,
    name: "Three.js",
    logo: "🌐",
    description: "A cross-browser JavaScript library and API used to create and display animated 3D computer graphics in a web browser using WebGL.",
    category: "graphics",
    tags: ["3D", "WebGL", "Animation", "Canvas", "Graphics"],
    stars: "99k",
    version: "r163",
    website: "https://threejs.org",
    github: "https://github.com/mrdoob/three.js",
    npm: "three",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 12,
    name: "Redux",
    logo: "🔄",
    description: "A predictable state container for JavaScript apps. Helps you write applications that behave consistently and run in different environments.",
    category: "state-management",
    tags: ["State", "React", "Flux", "Store", "Reducer"],
    stars: "60k",
    version: "5.0",
    website: "https://redux.js.org",
    github: "https://github.com/reduxjs/redux",
    npm: "redux",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 13,
    name: "Nuxt.js",
    logo: "💚",
    description: "An intuitive Vue framework providing server-side rendering, static site generation, and a powerful modular architecture.",
    category: "meta-framework",
    tags: ["Vue", "SSR", "SSG", "Full-stack", "Modules"],
    stars: "52k",
    version: "3.11",
    website: "https://nuxt.com",
    github: "https://github.com/nuxt/nuxt",
    npm: "nuxt",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 14,
    name: "Gatsby",
    logo: "🟣",
    description: "A React-based open source framework for creating websites and apps. Build anything you can imagine with over 2500 plugins.",
    category: "meta-framework",
    tags: ["React", "SSG", "GraphQL", "JAMstack", "Performance"],
    stars: "55k",
    version: "5.13",
    website: "https://www.gatsbyjs.com",
    github: "https://github.com/gatsbyjs/gatsby",
    npm: "gatsby",
    created: 2015,
    language: "JavaScript",
  },
  {
    id: 15,
    name: "RxJS",
    logo: "🔵",
    description: "A library for reactive programming using Observables, to make it easier to compose asynchronous or callback-based code.",
    category: "utility",
    tags: ["Reactive", "Observable", "Async", "Streams", "Angular"],
    stars: "30k",
    version: "7.8",
    website: "https://rxjs.dev",
    github: "https://github.com/ReactiveX/rxjs",
    npm: "rxjs",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 16,
    name: "Chart.js",
    logo: "📈",
    description: "Simple yet flexible JavaScript charting library for designers and developers, supporting 8 chart types with animations.",
    category: "data-viz",
    tags: ["Charts", "Canvas", "Visualization", "Responsive", "Animation"],
    stars: "63k",
    version: "4.4",
    website: "https://www.chartjs.org",
    github: "https://github.com/chartjs/Chart.js",
    npm: "chart.js",
    created: 2013,
    language: "JavaScript",
  },
  {
    id: 17,
    name: "GSAP",
    logo: "✨",
    description: "An industry-standard JavaScript animation library from GreenSock. Animate anything — CSS, SVG, DOM, canvas, React, Vue, WebGL, colors, strings, motion paths, generic objects.",
    category: "animation",
    tags: ["Animation", "Tweening", "Timeline", "SVG", "Performance"],
    stars: "19k",
    version: "3.12",
    website: "https://gsap.com",
    github: "https://github.com/greensock/GSAP",
    npm: "gsap",
    created: 2008,
    language: "JavaScript",
  },
  {
    id: 18,
    name: "Ember.js",
    logo: "🔥",
    description: "A productive, battle-tested JavaScript framework for building modern web applications. Includes everything you need to build rich UIs.",
    category: "ui-framework",
    tags: ["MVC", "Convention", "SPA", "Full-framework", "Router"],
    stars: "22k",
    version: "5.7",
    website: "https://emberjs.com",
    github: "https://github.com/emberjs/ember.js",
    npm: "ember-source",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 19,
    name: "Backbone.js",
    logo: "🦴",
    description: "Gives structure to web applications by providing models with key-value binding and custom events, collections, views with declarative event handling.",
    category: "ui-framework",
    tags: ["MVC", "Models", "Views", "REST", "Legacy"],
    stars: "28k",
    version: "1.4",
    website: "https://backbonejs.org",
    github: "https://github.com/jashkenas/backbone",
    npm: "backbone",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 20,
    name: "Zustand",
    logo: "🐻",
    description: "A small, fast and scalable bearbones state-management solution for React. Uses simplified flux principles with a comfortable API.",
    category: "state-management",
    tags: ["State", "React", "Lightweight", "Hooks", "Simple"],
    stars: "43k",
    version: "4.5",
    website: "https://zustand-demo.pmnd.rs",
    github: "https://github.com/pmndrs/zustand",
    npm: "zustand",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 21,
    name: "Vite",
    logo: "⚡",
    description: "Next generation frontend tooling. An extremely fast build tool and development server with instant HMR and optimized builds.",
    category: "build-tool",
    tags: ["Build", "HMR", "Dev Server", "ESM", "Bundler"],
    stars: "66k",
    version: "5.2",
    website: "https://vitejs.dev",
    github: "https://github.com/vitejs/vite",
    npm: "vite",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 22,
    name: "Webpack",
    logo: "📦",
    description: "A static module bundler for modern JavaScript applications. Builds a dependency graph of all modules your application needs.",
    category: "build-tool",
    tags: ["Bundler", "Modules", "Loaders", "Plugins", "Build"],
    stars: "64k",
    version: "5.91",
    website: "https://webpack.js.org",
    github: "https://github.com/webpack/webpack",
    npm: "webpack",
    created: 2012,
    language: "JavaScript",
  },
  {
    id: 23,
    name: "Jest",
    logo: "🃏",
    description: "A delightful JavaScript testing framework with a focus on simplicity. Works with React, Angular, Vue, Node, TypeScript, and more.",
    category: "testing",
    tags: ["Testing", "Unit Test", "Mocking", "Snapshot", "Coverage"],
    stars: "43k",
    version: "29.7",
    website: "https://jestjs.io",
    github: "https://github.com/jestjs/jest",
    npm: "jest",
    created: 2014,
    language: "TypeScript",
  },
  {
    id: 24,
    name: "Tailwind CSS",
    logo: "💨",
    description: "A utility-first CSS framework packed with classes that can be composed to build any design, directly in your markup.",
    category: "styling",
    tags: ["CSS", "Utility", "Styling", "Responsive", "Design"],
    stars: "79k",
    version: "3.4",
    website: "https://tailwindcss.com",
    github: "https://github.com/tailwindlabs/tailwindcss",
    npm: "tailwindcss",
    created: 2017,
    language: "JavaScript",
  },
  {
    id: 25,
    name: "Moment.js",
    logo: "🕐",
    description: "A JavaScript date library for parsing, validating, manipulating, and formatting dates. (Now in maintenance mode — consider alternatives.)",
    category: "utility",
    tags: ["Date", "Time", "Parsing", "Format", "Legacy"],
    stars: "47k",
    version: "2.30",
    website: "https://momentjs.com",
    github: "https://github.com/moment/moment",
    npm: "moment",
    created: 2011,
    language: "JavaScript",
  },
  {
    id: 26,
    name: "SvelteKit",
    logo: "🔶",
    description: "The fastest way to build Svelte apps. An app framework powered by Svelte with file-based routing, SSR, and API routes.",
    category: "meta-framework",
    tags: ["Svelte", "SSR", "SSG", "Full-stack", "Router"],
    stars: "18k",
    version: "2.5",
    website: "https://kit.svelte.dev",
    github: "https://github.com/sveltejs/kit",
    npm: "@sveltejs/kit",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 27,
    name: "Cypress",
    logo: "🌲",
    description: "Fast, easy and reliable testing for anything that runs in a browser. End-to-end testing, component testing, and visual regression.",
    category: "testing",
    tags: ["E2E", "Testing", "Browser", "Component", "Visual"],
    stars: "46k",
    version: "13.8",
    website: "https://www.cypress.io",
    github: "https://github.com/cypress-io/cypress",
    npm: "cypress",
    created: 2014,
    language: "TypeScript",
  },
  {
    id: 28,
    name: "Socket.IO",
    logo: "🔌",
    description: "Enables real-time, bidirectional and event-based communication between the browser and the server.",
    category: "backend",
    tags: ["WebSocket", "Real-time", "Events", "Node.js", "Chat"],
    stars: "60k",
    version: "4.7",
    website: "https://socket.io",
    github: "https://github.com/socketio/socket.io",
    npm: "socket.io",
    created: 2010,
    language: "TypeScript",
  },
  {
    id: 29,
    name: "Storybook",
    logo: "📖",
    description: "An open source tool for building UI components and pages in isolation. Streamlines UI development, testing, and documentation.",
    category: "tooling",
    tags: ["UI", "Documentation", "Component", "Testing", "Design"],
    stars: "83k",
    version: "8.0",
    website: "https://storybook.js.org",
    github: "https://github.com/storybookjs/storybook",
    npm: "storybook",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 30,
    name: "Solid.js",
    logo: "🔷",
    description: "A declarative, efficient and flexible JavaScript library for building user interfaces with fine-grained reactivity and no virtual DOM.",
    category: "ui-framework",
    tags: ["Reactive", "No Virtual DOM", "Performance", "Signals", "JSX"],
    stars: "31k",
    version: "1.8",
    website: "https://www.solidjs.com",
    github: "https://github.com/solidjs/solid",
    npm: "solid-js",
    created: 2018,
    language: "TypeScript",
  },
  {
    id: 31,
    name: "Remix",
    logo: "💿",
    description: "A full-stack web framework built on web standards that lets you focus on the user interface and work back through web fundamentals to deliver fast and resilient experiences.",
    category: "meta-framework",
    tags: ["React", "SSR", "Full-stack", "Web Standards", "Routing"],
    stars: "29k",
    version: "2.9",
    website: "https://remix.run",
    github: "https://github.com/remix-run/remix",
    npm: "@remix-run/react",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 32,
    name: "Astro",
    logo: "🚀",
    description: "The web framework for content-driven websites. Astro builds fast websites by shipping zero JavaScript by default with its unique island architecture.",
    category: "meta-framework",
    tags: ["SSG", "Islands", "Performance", "Content", "Multi-framework"],
    stars: "43k",
    version: "4.8",
    website: "https://astro.build",
    github: "https://github.com/withastro/astro",
    npm: "astro",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 33,
    name: "Vitest",
    logo: "🧪",
    description: "A blazing fast unit testing framework powered by Vite. Native ESM, TypeScript, and JSX support out of the box with a Jest-compatible API.",
    category: "testing",
    tags: ["Testing", "Unit Test", "Vite", "ESM", "Coverage"],
    stars: "12k",
    version: "1.6",
    website: "https://vitest.dev",
    github: "https://github.com/vitest-dev/vitest",
    npm: "vitest",
    created: 2021,
    language: "TypeScript",
  },
  {
    id: 34,
    name: "Playwright",
    logo: "🎭",
    description: "A reliable end-to-end testing framework for modern web apps. Supports Chromium, Firefox, and WebKit with a single API across all platforms.",
    category: "testing",
    tags: ["E2E", "Testing", "Browser", "Cross-browser", "Automation"],
    stars: "63k",
    version: "1.44",
    website: "https://playwright.dev",
    github: "https://github.com/microsoft/playwright",
    npm: "@playwright/test",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 35,
    name: "Jotai",
    logo: "⚛️",
    description: "Primitive and flexible state management for React. Takes a bottom-up atomic approach to global React state management with a minimal API.",
    category: "state-management",
    tags: ["State", "React", "Atomic", "Hooks", "Lightweight"],
    stars: "17k",
    version: "2.8",
    website: "https://jotai.org",
    github: "https://github.com/pmndrs/jotai",
    npm: "jotai",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 36,
    name: "MobX",
    logo: "🔮",
    description: "Simple, scalable state management. MobX makes state management simple by transparently applying functional reactive programming principles.",
    category: "state-management",
    tags: ["State", "Reactive", "Observable", "Decorators", "OOP"],
    stars: "27k",
    version: "6.12",
    website: "https://mobx.js.org",
    github: "https://github.com/mobxjs/mobx",
    npm: "mobx",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 37,
    name: "TanStack Query",
    logo: "🔍",
    description: "Powerful asynchronous state management for React, Vue, Solid, and Svelte. Often called React Query, it simplifies fetching, caching, syncing, and updating server state.",
    category: "utility",
    tags: ["Data Fetching", "Caching", "Async", "Server State", "React"],
    stars: "39k",
    version: "5.40",
    website: "https://tanstack.com/query",
    github: "https://github.com/TanStack/query",
    npm: "@tanstack/react-query",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 38,
    name: "Zod",
    logo: "🛡️",
    description: "TypeScript-first schema declaration and validation library. Define schemas once and use them for both TypeScript types and runtime validation.",
    category: "utility",
    tags: ["Validation", "TypeScript", "Schema", "Types", "Parsing"],
    stars: "31k",
    version: "3.23",
    website: "https://zod.dev",
    github: "https://github.com/colinhacks/zod",
    npm: "zod",
    created: 2020,
    language: "TypeScript",
  },
  {
    id: 39,
    name: "Framer Motion",
    logo: "🎬",
    description: "A production-ready motion library for React. Provides a simple, declarative API for animations and gestures, from simple transitions to complex orchestrations.",
    category: "animation",
    tags: ["Animation", "React", "Gestures", "Motion", "Transitions"],
    stars: "23k",
    version: "11.2",
    website: "https://www.framer.com/motion",
    github: "https://github.com/framer/motion",
    npm: "framer-motion",
    created: 2019,
    language: "TypeScript",
  },
  {
    id: 40,
    name: "Anime.js",
    logo: "✏️",
    description: "A lightweight JavaScript animation library with a simple yet powerful API. Animate CSS properties, SVG, DOM attributes, and JavaScript objects.",
    category: "animation",
    tags: ["Animation", "CSS", "SVG", "Lightweight", "Timeline"],
    stars: "49k",
    version: "3.2",
    website: "https://animejs.com",
    github: "https://github.com/juliangarnier/anime",
    npm: "animejs",
    created: 2016,
    language: "JavaScript",
  },
  {
    id: 41,
    name: "PixiJS",
    logo: "🎮",
    description: "The HTML5 Creation Engine. Create beautiful digital content with the fastest, most flexible 2D WebGL renderer, with a fallback to HTML5 Canvas.",
    category: "graphics",
    tags: ["2D", "WebGL", "Canvas", "Rendering", "Games"],
    stars: "43k",
    version: "8.1",
    website: "https://pixijs.com",
    github: "https://github.com/pixijs/pixijs",
    npm: "pixi.js",
    created: 2013,
    language: "TypeScript",
  },
  {
    id: 42,
    name: "Fastify",
    logo: "⚡",
    description: "Fast and low overhead web framework for Node.js. One of the fastest web frameworks available, with a rich plugin ecosystem and great developer experience.",
    category: "backend",
    tags: ["Node.js", "HTTP", "REST", "Performance", "Plugins"],
    stars: "31k",
    version: "4.27",
    website: "https://fastify.dev",
    github: "https://github.com/fastify/fastify",
    npm: "fastify",
    created: 2016,
    language: "JavaScript",
  },
  {
    id: 43,
    name: "NestJS",
    logo: "🐈",
    description: "A progressive Node.js framework for building efficient, reliable and scalable server-side applications. Built with TypeScript and heavily inspired by Angular.",
    category: "backend",
    tags: ["Node.js", "TypeScript", "Enterprise", "Decorators", "Modules"],
    stars: "66k",
    version: "10.3",
    website: "https://nestjs.com",
    github: "https://github.com/nestjs/nest",
    npm: "@nestjs/core",
    created: 2017,
    language: "TypeScript",
  },
  {
    id: 44,
    name: "Mongoose",
    logo: "🍃",
    description: "Elegant MongoDB object modeling for Node.js. Provides a straightforward, schema-based solution to model application data with built-in type casting and validation.",
    category: "backend",
    tags: ["MongoDB", "ODM", "Node.js", "Schema", "Database"],
    stars: "26k",
    version: "8.4",
    website: "https://mongoosejs.com",
    github: "https://github.com/Automattic/mongoose",
    npm: "mongoose",
    created: 2010,
    language: "JavaScript",
  },
  {
    id: 45,
    name: "Day.js",
    logo: "📅",
    description: "A minimalist 2kB JavaScript library that parses, validates, manipulates, and displays dates and times for modern browsers with a largely Moment.js-compatible API.",
    category: "utility",
    tags: ["Date", "Time", "Lightweight", "Immutable", "i18n"],
    stars: "46k",
    version: "1.11",
    website: "https://day.js.org",
    github: "https://github.com/iamkun/dayjs",
    npm: "dayjs",
    created: 2018,
    language: "JavaScript",
  },
  {
    id: 46,
    name: "styled-components",
    logo: "💅",
    description: "Visual primitives for the component age. Uses tagged template literals to style React components, keeping CSS co-located with the component that uses it.",
    category: "styling",
    tags: ["CSS-in-JS", "React", "Theming", "Dynamic Styles", "Component"],
    stars: "40k",
    version: "6.1",
    website: "https://styled-components.com",
    github: "https://github.com/styled-components/styled-components",
    npm: "styled-components",
    created: 2016,
    language: "TypeScript",
  },
  {
    id: 47,
    name: "Rollup",
    logo: "📜",
    description: "A module bundler for JavaScript which compiles small pieces of code into something larger and more complex. Ideal for library authors thanks to its tree-shaking.",
    category: "build-tool",
    tags: ["Bundler", "ESM", "Tree-shaking", "Library", "Modules"],
    stars: "24k",
    version: "4.18",
    website: "https://rollupjs.org",
    github: "https://github.com/rollup/rollup",
    npm: "rollup",
    created: 2015,
    language: "TypeScript",
  },
  {
    id: 48,
    name: "esbuild",
    logo: "⚡",
    description: "An extremely fast JavaScript and TypeScript bundler and minifier, written in Go. 10–100x faster than other bundlers, used as the core of many modern tools.",
    category: "build-tool",
    tags: ["Bundler", "Fast", "Go", "Minifier", "TypeScript"],
    stars: "37k",
    version: "0.21",
    website: "https://esbuild.github.io",
    github: "https://github.com/evanw/esbuild",
    npm: "esbuild",
    created: 2020,
    language: "Go",
  },
  {
    id: 49,
    name: "Prettier",
    logo: "✨",
    description: "An opinionated code formatter that supports many languages. Enforces a consistent style by parsing your code and reprinting it with its own rules.",
    category: "tooling",
    tags: ["Formatter", "Code Style", "Linting", "Multi-language", "Opinionated"],
    stars: "48k",
    version: "3.3",
    website: "https://prettier.io",
    github: "https://github.com/prettier/prettier",
    npm: "prettier",
    created: 2017,
    language: "JavaScript",
  },
  {
    id: 50,
    name: "ESLint",
    logo: "🔍",
    description: "Find and fix problems in your JavaScript code. A fully pluggable tool for identifying and reporting on patterns in ECMAScript/JavaScript code.",
    category: "tooling",
    tags: ["Linting", "Code Quality", "Rules", "Plugins", "ECMAScript"],
    stars: "24k",
    version: "9.4",
    website: "https://eslint.org",
    github: "https://github.com/eslint/eslint",
    npm: "eslint",
    created: 2013,
    language: "JavaScript",
  },
];

const categories = [
  { id: "all", label: "All Libraries" },
  { id: "ui-framework", label: "UI Frameworks" },
  { id: "meta-framework", label: "Meta Frameworks" },
  { id: "state-management", label: "State Management" },
  { id: "utility", label: "Utilities" },
  { id: "backend", label: "Backend" },
  { id: "data-viz", label: "Data Visualization" },
  { id: "animation", label: "Animation" },
  { id: "graphics", label: "3D & Graphics" },
  { id: "build-tool", label: "Build Tools" },
  { id: "testing", label: "Testing" },
  { id: "styling", label: "Styling" },
  { id: "tooling", label: "Tooling" },
];
